# This file was generated by GoReleaser. DO NOT EDIT.
cask "equationlabs-php-cli" do
  desc "EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)"
  homepage "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
  version "1.1.0-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equationlabs-php-cli"

  on_macos do
    url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-darwin-all-all.tar.gz"
    sha256 "db5d93f2cfb44f238a538d022a19ae4b061867a6865d3f933cd480bde9fd966b"
  end

  on_linux do
    on_intel do
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-amd64-x86_64.tar.gz"
      sha256 "7226d622810331ec10c0e7669d1d6f678122d8e02baee48f5914a652fbc14b49"
    end
    on_arm do
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-arm64-arm64.tar.gz"
      sha256 "cf80212c3fcfd9fcbe54946468af7c1364aebad4f1e0601e9b9c5c0d850a1c78"
    end
  end

  # No zap stanza required
end
