# This file was generated by GoReleaser. DO NOT EDIT.
cask "equationlabs-php-cli" do
  desc "EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)"
  homepage "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
  version "1.1.0-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equationlabs-php-cli"

  on_macos do
    url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-darwin-all-all.tar.gz"
    sha256 "0d4c1682d3cd5f599e10c22b1ef3e595983d15b1dcb06229ee9cc87e7a42a037"
  end

  on_linux do
    on_intel do
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-amd64-x86_64.tar.gz"
      sha256 "3a8581fcd5aad41efb28c4cbc783404f4a793126a05461c4be306fb0a94702f3"
    end
    on_arm do
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-arm64-arm64.tar.gz"
      sha256 "9d423c9458dd058a5f124ade0bb2222c1909271875e4233ab245fdffedeb4442"
    end
  end

  # No zap stanza required
end
