# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EquationlabsPhpCli < Formula
  desc "EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)"
  homepage "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
  version "1.1.0-rc.1"
  license "MIT"

  depends_on "composer" => :optional
  depends_on "git" => :optional

  on_macos do
    url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-darwin-all-all.tar.gz"
    sha256 "0d4c1682d3cd5f599e10c22b1ef3e595983d15b1dcb06229ee9cc87e7a42a037"

    def install
      bin.install "equationlabs-php-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-amd64-x86_64.tar.gz"
      sha256 "3a8581fcd5aad41efb28c4cbc783404f4a793126a05461c4be306fb0a94702f3"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-arm64-arm64.tar.gz"
      sha256 "9d423c9458dd058a5f124ade0bb2222c1909271875e4233ab245fdffedeb4442"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completions, type the following command for instructions:
        equationlabs-php-cli completion --help
    EOS
  end

  test do
    system "#{bin}/equationlabs-php-cli --version"
  end
end
