# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EquationlabsPhpCli < Formula
  desc "EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)"
  homepage "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
  version "1.1.0-rc.1"
  license "MIT"

  depends_on "composer" => :optional
  depends_on "git" => :optional

  on_macos do
    url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-darwin-all-all.tar.gz"
    sha256 "db5d93f2cfb44f238a538d022a19ae4b061867a6865d3f933cd480bde9fd966b"

    def install
      bin.install "equationlabs-php-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-amd64-x86_64.tar.gz"
      sha256 "7226d622810331ec10c0e7669d1d6f678122d8e02baee48f5914a652fbc14b49"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0-rc.1/equationlabs-php-cli-v1.1.0-rc.1-linux-arm64-arm64.tar.gz"
      sha256 "cf80212c3fcfd9fcbe54946468af7c1364aebad4f1e0601e9b9c5c0d850a1c78"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completions, type the following command for instructions:
        equationlabs-php-cli completion --help
    EOS
  end

  test do
    system "#{bin}/equationlabs-php-cli --version"
  end
end
