# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EquationlabsPhpCli < Formula
  desc "EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)"
  homepage "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
  version "2.0.2"
  license "MIT"

  depends_on "composer"

  on_macos do
    url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v2.0.2/equationlabs-php-cli_darwin_all.tar.gz"
    sha256 "c01a2e20f213c3e8b6549cbd86ffb821e898909cb822d49df0bfe4310b2e0836"

    def install
      bin.install "equationlabs-php-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v2.0.2/equationlabs-php-cli_linux_amd64.tar.gz"
      sha256 "e0ddbb43c365b62fbea48957c07e9df2e957fbb9d7154b4de8cd512fd8477aaa"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v2.0.2/equationlabs-php-cli_linux_arm64.tar.gz"
      sha256 "4769f880d4dce54cee0ad3cbe0e374adf40f56f133699e82b97c6222b5fa5ff4"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completions, type the following command for instructions:
        equationlabs-php-cli completion --help
    EOS
  end

  test do
    system "#{bin}/equationlabs-php-cli --version"
  end
end
