# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EquationlabsPhpCli < Formula
  desc "EquationLabs PHP CLI creates scaffolded projects following equationlabs development guidelines (DDD, CQRS, Testing, Automation)"
  homepage "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator"
  version "1.1.0"
  license "MIT"

  depends_on "composer" => :optional
  depends_on "git" => :optional

  on_macos do
    url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0/equationlabs-php-cli-v1.1.0-darwin-all-all.tar.gz"
    sha256 "98ce7df53c43a07d12700ae09c1c273bdf264f63eefea8a36e093effafb32ef7"

    def install
      bin.install "equationlabs-php-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0/equationlabs-php-cli-v1.1.0-linux-amd64-x86_64.tar.gz"
      sha256 "68cb0d4e3bf52fe270e8202834a9c4521c5e2786d2ac5210275aa0fe03a0c0ca"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/equationlabs/eqlabs-tools-php-skeleton-creator/releases/download/v1.1.0/equationlabs-php-cli-v1.1.0-linux-arm64-arm64.tar.gz"
      sha256 "774ec47afdf004f155c30264858969b937ecaaf6a3c342ed147046ffb509f231"
      def install
        bin.install "equationlabs-php-cli"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completions, type the following command for instructions:
        equationlabs-php-cli completion --help
    EOS
  end

  test do
    system "#{bin}/equationlabs-php-cli --version"
  end
end
